config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'pages#index'
  get 'about' => 'pages#about'

  get ':slug' => 'home#show', as: 'home_category'

  resources :articles, only: :show
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :image
  has_and_belongs_to_many :categories

  validates :categories, length: { minimum: 1, message: 'debes seleccionar una categoría' }
  validates :title, :body, :image, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :articles

  validates :name, presence: true

  scope :with_articles, -> { joins(:articles).distinct }

  before_save do
    self.slug = name.split.join('-').downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def show
    @article = Article.find params[:id]
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @articles = Article.all
    @categories = Category.with_articles
  end

  def show
    category = Category.find_by(slug: params[:slug])
    @categories = Category.with_articles
    @articles = category.articles

    render 'pages/index'
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index
    @articles = Article.all
    @categories = Category.with_articles
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/show.html.haml
/ Breadcrumb Area
%section.breadcrumb-area
  .container
    .row
      .col-md-12
        .breadcrumb-box
          %ul.list-unstyled.list-inline
            %li.list-inline-item
              %a{:href => "/"} Inicio
              %i.fa.fa-angle-right
            %li.list-inline-item= @article.title
/ End Breadcrumb Area
/ News Details Area
%section.category-details
  .container
    .row
      .col-lg-8.col-md-12
        .row
          .col-md-12
            .news-heading
              %h4= @article.title
              %ul.list-unstyled.list-inline
                %li.list-inline-item
                  %i.fa.fa-user-o
                  %a{:href => "#"} Administrador
                %li.list-inline-item
                  %i.fa.fa-calendar
                  = l(@article.created_at, format: "%B %d, %Y")
                -# %li.list-inline-item
                -#   %i.fa.fa-commenting-o
                -#   %a{:href => "#"} (09 Comments)
            .news-content
              = image_tag @article.image, class: 'img-fluid'
              = @article.body.html_safe
          .col-md-12
            .social-tag.d-flex.justify-content-between
              .social
                %ul.list-unstyled.list-inline
                  - @article.categories.each do |category|
                    %li.list-inline-item
                      = link_to category.name.upcase, home_category_path(category)
 
          .col-md-12
            -# .news-author.d-flex
            -#   .author-img
            -#     %img{:alt => "", :src => "images/author.jpg"}/
            -#   .author-content
            -#     %h6
            -#       Author :
            -#       %a{:href => ""} Md Tahmidur Rahman
            -#     %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi doloribus unde molestias laborum delectus adipisci, eos repellat in debitis cum impedit numquam, architecto, facilis.
            -#     %ul.list-unstyled.list-inline.f-social
            -#       %li.list-inline-item
            -#         %a{:href => ""}
            -#           %i.fa.fa-facebook
            -#       %li.list-inline-item
            -#         %a{:href => ""}
            -#           %i.fa.fa-twitter
            -#       %li.list-inline-item
            -#         %a{:href => ""}
            -#           %i.fa.fa-linkedin
            -#       %li.list-inline-item
            -#         %a{:href => ""}
            -#           %i.fa.fa-google-plus
            -#       %li.list-inline-item
            -#         %a{:href => ""}
            -#           %i.fa.fa-rss
            -#       %li.list-inline-item
            -#         %a{:href => ""}
            -#           %i.fa.fa-youtube
          .col-md-12  
            =# render 'shared/comments_list'
          .col-md-12
            =# render 'shared/comments_form'
      .col-lg-4.col-md-12
        .row
          .col-md-12
            = render 'shared/follow_us_sidebar'
          .col-md-12
            =# render 'shared/tab_widget'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    %title Aaaj
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
  %body
    = render 'shared/preloader'
    = render 'shared/logo_area'
    = render 'shared/menu_area'
    = render 'shared/mobile_menu_area'
    = yield
    = render 'shared/footer_area'
    = render 'shared/footer_btm'
    = javascript_pack_tag 'application'
    = javascript_pack_tag 'custom'

app/views/pages/about.html.haml
/ About Area
%section.about-us
  .container
    .row
      .col-md-12
        .sec-top.text-center
          %h4 ¿QUIENES SOMOS?
      .col-lg-6.col-md-12
        .about-box
          %h4
            AAAJ y su gente
          %p
            Podría ser un cuento de Sacheri, de Fontanarrosa, de Galeano o hasta del gordo Caseari.
            Era un grupo de siete u ocho pibes del barrio de la paternal que tenían un sueño, tener su programa de radio. 
            Claro por ese entonces argentinos juniors era como los gitanos, no tenia cancha y jugaba de local en deportivo español, huracán, atlanta, en boca. Claro no tenia una localia firme, pero cada vez que terminaba un partido estos adolescentes se quedaban hasta altas horas de la noche hablando y soñando. Por que deportivo español y hasta chacarita tenia su audición, y como el bicho de la paternal no iba a tener su programa de radio. Fue así que rompiendo algunas alcancías, buscando publicidad en el kiosco de la esquina, sobre san blas o jonte, la veterinaria, hasta la tintorería de un chino o de un japones ahí sobre la calle terrada, iban poniendo algunos pesos y fue así como argentinos juniors y su gente armo su primer programa, era en fm sol, juan b. justo y añasco por ahí, sobre la calle añasco. Claro que si vos cruzabas Juan B. justo para el otro lado, aquel 3 de octubre de 1990 tal vez los escucharás con ruido, pero si estabas del lado par lo escuchabas perfecto. Si cruzabas la av. San Martin, ahí la señal se te iba, pero lo mágico fue el primer día, el otro fin de semana cuando argentinos jugo de local. Me parece estoy casi seguro que fue contra huracán, la gente comentaba " che escucharon argentinos tiene su programa de radio", tiene la audición. Claro por ese entonces se llama audición al programa, por que uno tenia que esperar treinta segundos que el gordo Muñoz o Victor Hugo diga el flash informativo: Argentinos juniors (treinta segundos) y no llegabas a enterarte de nada. y ahora ya se cumplen 29 años que argentinos juniors y su Gente tiene su programa y vos todos los miércoles a las 22 horas podes sintonizar am 610 y que vas a conseguir?. Te vas a informar, vas a formar una idea, te vas a entretener y de eso se trata que cada miércoles Argentinos Juniors y su Gente entre adentro de tu corazón.
      .col-lg-6.col-md-12
        .about-img
          = image_tag 'about.jpg', class: 'img-fluid'   
-#       .col-md-12
-#         .team
-#           .sec-title
-#             %h5 Staff
-#           .team-slider.owl-carousel
-#             .slider-item.text-center
-#               = image_tag 'about.jpg', class: 'team-1.jpg'
-#               %h5
-#                 %a{:href => ""} Mr. John Doe
-#               %p Founder
-#               %ul.list-unstyled.list-inline
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-facebook
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-twitter
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-google-plus
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-linkedin
-#             .slider-item.text-center
-#               = image_tag 'about.jpg', class: 'team-1.jpg'
-#               %h5
-#                 %a{:href => ""} Ms. Jasica Brown
-#               %p Editor
-#               %ul.list-unstyled.list-inline
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-facebook
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-twitter
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-linkedin
-#             .slider-item.text-center
-#               = image_tag 'about.jpg', class: 'team-1.jpg'
-#               %h5
-#                 %a{:href => ""} Mr. Adam Green
-#               %p Publisher
-#               %ul.list-unstyled.list-inline
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-facebook
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-twitter
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-google-plus
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-linkedin
-#             .slider-item.text-center
-#               = image_tag 'about.jpg', class: 'team-1.jpg'
-#               %h5
-#                 %a{:href => ""} Ms. Katrina Jun
-#               %p Photographer
-#               %ul.list-unstyled.list-inline
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-facebook
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-twitter
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-google-plus
-#             .slider-item.text-center
-#               = image_tag 'about.jpg', class: 'team-1.jpg'
-#               %h5
-#                 %a{:href => ""} Mr. David Show
-#               %p Manager
-#               %ul.list-unstyled.list-inline
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-facebook
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-twitter
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-google-plus
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-linkedin
-#             .slider-item.text-center
-#               = image_tag 'about.jpg', class: 'team-1.jpg'
-#               %h5
-#                 %a{:href => ""} Ms. Tailor Brown
-#               %p Officer
-#               %ul.list-unstyled.list-inline
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-facebook
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-twitter
-#                 %li.list-inline-item
-#                   %a{:href => ""}
-#                     %i.fa.fa-linkedin
-# / End About Area

app/views/pages/index.html.haml
=# render 'shared/top_news'
= render 'shared/slider_area'
= render 'shared/news_area'

app/views/shared/_comments_form.html.haml
.comment-form
  .sec-title
    %h5 Leave Your Comment
  %form.com-form{:action => "#"}
    .row
      .col-md-6
        %input{:name => "name", :placeholder => "Enter Your Name", :type => "text", :value => ""}/
      .col-md-6
        %input{:name => "email", :placeholder => "Enter Your Email", :type => "text", :value => ""}/
      .col-md-12
        %textarea{:name => "name", :placeholder => "Your Comment Here"}
        %button{:name => "button", :type => "button"} Post Comment

app/views/shared/_comments_list.html.haml
.comment-sec
  .sec-title
    %h5
      Comments
      %span (03)
  .comment-box.d-flex
    .comment-img
      %a{:href => ""}
        %img{:alt => "", :src => "images/comm-1.jpg"}/
    .comment-con
      %ul.list-unstyled.list-inline
        %li.list-inline-item
          %a{:href => ""} John Doe
        %li.list-inline-item
          %a{:href => ""} Reply
      %span Feb 11, 2019 at 3:15pm
      %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit nam, non magnam molestias aspernatur. Magni suscipit sequi harum odit sunt est.
  .comment-box.comment-box2.d-flex
    .comment-img
      %a{:href => ""}
        %img{:alt => "", :src => "images/comm-2.jpg"}/
    .comment-con
      %ul.list-unstyled.list-inline
        %li.list-inline-item
          %a{:href => ""} Mary Chang
        %li.list-inline-item
          %a{:href => ""} Reply
      %span Feb 11, 2019 at 3:15pm
      %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit nam, non magnam molestias aspernatur. Magni suscipit sequi harum odit sunt est.
  .comment-box.d-flex
    .comment-img
      %a{:href => ""}
        %img{:alt => "", :src => "images/comm-3.jpg"}/
    .comment-con
      %ul.list-unstyled.list-inline
        %li.list-inline-item
          %a{:href => ""} Kate Brown
        %li.list-inline-item
          %a{:href => ""} Reply
      %span Feb 11, 2019 at 3:15pm
      %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit nam, non magnam molestias aspernatur. Magni suscipit sequi harum odit sunt est.

app/views/shared/_follow_us_footer.html.haml
%ul.list-unstyled.list-inline.f-social
  %li.list-inline-item
    = link_to "https://www.facebook.com/aaajysugente/", target: "blank" do
      %i.fa.fa-facebook
  %li.list-inline-item
    = link_to "https://twitter.com/aaajysugente", target: "blank" do
      %i.fa.fa-twitter
  %li.list-inline-item
    = link_to "https://www.instagram.com/aaajysugente/", target: "blank" do
      %i.fa.fa-instagram
  %li.list-inline-item
    = link_to "https://www.youtube.com/channel/UCcatJNy2S6AzqVUJ8NiFR9w/", target: "blank" do
      %i.fa.fa-youtube

app/views/shared/_footer_btm.html.haml
%section.footer-btm
  .container
    .row
      .col-md-12
        .copyright-text
          %p
            Copyright © 2019 | Designed With
            %i.fa.fa-heart
            by
            %a{:href => "http://luigibyte.com.ar", :target => "_blank"} luigibyte
      -# .col-md-6
      -#   .ftb-menu.text-right
      -#     %ul.list-unstyled.list-inline
      -#       %li.list-inline-item
      -#         %a{:href => ""} Home
      -#       %li.list-inline-item
      -#         %a{:href => ""} Map
      -#       %li.list-inline-item
      -#         %a{:href => ""} Site Map
      -#       %li.list-inline-item
      -#         %a{:href => ""} Location
      -#       %li.list-inline-item
      -#         %a{:href => ""} Blog
  .back-to-top.text-center
    %a{"data-scroll" => "", :href => "#btt"}
      %i.fa.fa-angle-up

app/views/shared/_gallery_area.html.haml
%section.gallery-area
  .container
    .row
      .col-lg-8.col-md-12
        .image-gallery
          .sec-title
            %h5
              Pictures
              %i.fa.fa-caret-right
          .image-gallery-box
            .gallery-slider.owl-carousel
              .gallery-item
                = image_tag 'gallery-image-1.jpg', class: 'img-fluid'
                .gallery-content
                  %p
                    %a{:href => ""} This handout will help you understand how paragraphs are formed. It is usually composed of several sentences that together develop one.
              .gallery-item
                = image_tag 'gallery-image-2.jpg', class: 'img-fluid'
                .gallery-content
                  %p
                    %a{:href => ""} This handout will help you understand how paragraphs are formed. It is usually composed of several sentences that together develop one.
          .image-gallery-list.d-flex.justify-content-between
            .gallery-list-item
              = image_tag 'popular-10.jpg', class: 'gallery-img'
              .fc-icon
                %a{:href => ""}
                  %i.fa.fa-camera
            .gallery-list-item
              = image_tag 'popular-7.jpg', class: 'gallery-img'
              .fc-icon
                %a{:href => ""}
                  %i.fa.fa-camera
            .gallery-list-item
              = image_tag 'popular-11.jpg', class: 'gallery-img'
              .fc-icon
                %a{:href => "#"}
                  %i.fa.fa-camera
            .gallery-list-item
              = image_tag 'popular-5.jpg', class: 'gallery-img'
              .fc-icon
                %a{:href => "#"}
                  %i.fa.fa-camera
      .col-lg-4.col-md-12
        .video-gallery
          .sec-title
            %h5
              Videos
              %i.fa.fa-caret-right
          .video-lg
            .video-table
              .video-tablecell.text-center
                %a#video-btn{:href => "https://www.youtube.com/watch?v=uXFUl0KcIkA"}
                  %i.fa.fa-play
          .video-list
            .video-list-item.d-flex
              .vid-img
                = image_tag 'lt-sm-9.jpg'
                %a{:href => "#"}
                  %i.fa.fa-video-camera
              .img-content
                %p
                  %a{:href => "#"} These sentences are select from online news.
                %span 2 minutes ago
            .video-list-item.d-flex
              .vid-img
                = image_tag 'lt-sm-11.jpg'
                %a{:href => "#"}
                  %i.fa.fa-video-camera
              .img-content
                %p
                  %a{:href => "#"} These sentences are select from online news.
                %span 42 minutes ago

app/views/shared/_logo_area.html.haml
%section.logo-area#btt
  .container
    .row
      .col-md-6
        .logo
          = link_to root_path do
            = image_tag 'logo.png', class: 'img-fluid', width: '400'
      .col-md-6
        .searchbar.text-right
          %form{:action => "#"}
            %input{:placeholder => "Buscar...", :required => "", :type => "text"}/
            %button{:type => "submit"}
              %i.fa.fa-search

app/views/shared/_menu_area.html.haml
%section.menu-area
  .container
    .row
      .col-md-9
        .main-menu
          %ul.list-unstyled.list-inline
            %li.list-inline-item
              %a
                INICIO
                %i.fa.fa-angle-down
              %ul.dropdown.list-unstyled
                - Category.all.each do |category|
                  %li= link_to category.name, home_category_path(category.slug)
            %li.list-inline-item
              = link_to "FUTBOL PROFESIONAL", home_category_path('futbol-profesional')
            %li.list-inline-item
              = link_to '¿QUIENES SOMOS?', about_path
      .col-md-3
        .clock.text-right
          %span#dg-clock

app/views/shared/_mobile_menu_area.html.haml
%section.mobile-menu-area
  .container
    .row
      .col-md-12
        .mobile-menu
          %nav#dropdown
            %a{:href => ""}
              = image_tag 'logo.png'
            %ul.list-unstyled
              %li
                %a INICIO
                %ul.list-unstyled
                  - Category.all.each do |category|
                    %li= link_to category.name, home_category_path(category.slug)
              %li
                = link_to "FUTBOL PROFESIONAL", home_category_path('futbol-profesional')

app/views/shared/_news_area.html.haml
%section.news-area
  .container
    .row
      .col-lg-8.col-md-12
        .row
          .col-md-12
            .latest-news
              .tab-box.d-flex.justify-content-between
                .sec-title
                  %h5 Últimas noticias
                / Nav tabs
                %ul.nav.nav-tabs{:role => "tablist"}
                  - @categories.each_with_index do |category, index|
                    %li.nav-item
                      %a.nav-link{"data-toggle" => "tab", :href => "##{category.slug}", class: index == 0 ? 'active' : ''}= category.name
              / Tab panes
              .tab-content
                - @categories.each_with_index do |category, index|
                  .tab-pane.fade.show{:role => "tabpanel", id: category.slug, class: index == 0 ? 'active' : ''}
                    .row
                      .col-md-6
                        .lt-item-bg
                          = link_to article_path(category.articles.last) do
                            = image_tag category.articles.last.image.variant(resize_to_fill: [500, 326], gravity: 'center'), class: 'img-fluid'
                          %h6
                            = link_to category.articles.last.title, article_path(category.articles.last)
                          %ul.list-unstyled.list-inline
                            - category.articles.last.categories.each do |category|
                              %li.list-inline-item= category.name.upcase
                            %li.list-inline-item= l(category.articles.last.created_at, format: "%B %d, %Y")
                          =# category.articles.last.body
                      .col-md-6
                        - category.articles.each do |article|
                          .lt-item-sm.d-flex
                            .lt-img
                              = link_to article_path(article) do
                                = image_tag category.articles.last.image.variant(resize_to_fill: [101, 81], gravity: 'center')
                            .img-content
                              %p
                                = link_to article.title, article_path(article)
                              %span= l(article.created_at, format: "%B %d, %Y")
      .col-lg-4.col-md-12
        .row
          .col-md-12
            = render 'shared/follow_us_sidebar'

app/views/shared/_preloader.html.haml
.preloader
  .load-list
    .load
    .load.load2

app/views/shared/_slider_area.html.haml
%section.slider-area
  .container
    .row
      .col-lg-8.col-md-12.padding-fix-r
        .owl-carousel.owl-slider
          - @articles.each do |article|
            .slider-content
              = image_tag article.image.variant(resize_to_fill: [1000, 639], gravity: 'center'), class: 'img-fluid'
              .slider-layer
                %p
                  = link_to article.title, article_path(article)
                %ul.list-unstyled.list-inline
                  - article.categories.each do |category|
                    %li.list-inline-item= category.name.upcase
                  %li.list-inline-item= l(article.created_at, format: "%B %d, %Y")
      .col-lg-4.col-md-12.slider-fix
        - @articles.take(2).each_with_index do |article, index|
          .slider-sidebar{class: index.zero? ? 'sidebar-o' : ''}
            = image_tag article.image.variant(resize_to_fill: [500, 327], gravity: 'center'), class: 'img-fluid'
            .sidebar-layer
              %p
                = link_to article.title, article_path(article)
              %ul.list-unstyled.list-inline
                - article.categories.each do |category|
                  %li.list-inline-item= category.name.upcase
                %li.list-inline-item= l(article.created_at, format: "%B %d, %Y")

app/views/shared/_tab_widget.html.haml
.tab-widget
  %ul.nav.nav-tabs{:role => "tablist"}
    %li.nav-item
      %a.nav-link.active{"data-toggle" => "tab", :href => "#recent"} Recent
    %li.nav-item
      %a.nav-link{"data-toggle" => "tab", :href => "#popular"} Popular
    %li.nav-item
      %a.nav-link{"data-toggle" => "tab", :href => "#comment"} Comment
  / Tab panes
  .tab-content
    #recent.tab-pane.fade.show.active{:role => "tabpanel"}
      .rec-item.d-flex
        .rec-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/lt-sm-6.jpg"}/
        .img-content
          %p
            %a{:href => ""} These sentences are selected from various online news.
          %span 20 Seconds ago
      .rec-item.d-flex
        .rec-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/lt-sm-11.jpg"}/
        .img-content
          %p
            %a{:href => ""} These sentences are selected from various online news.
          %span 4 minutes ago
      .rec-item.d-flex
        .rec-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/lt-sm-7.jpg"}/
        .img-content
          %p
            %a{:href => ""} These sentences are selected from various online news.
          %span 47 minutes ago
      .rec-item.d-flex
        .rec-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/lt-sm-4.jpg"}/
        .img-content
          %p
            %a{:href => ""} These sentences are selected from various online news.
          %span 1 Hours ago
    #popular.tab-pane.fade{:role => "tabpanel"}
      .pop-item.d-flex
        .pop-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/lt-sm-3.jpg"}/
        .img-content
          %p
            %a{:href => ""} These sentences are selected from various online news.
          %ul.list-unstyled.list-inline
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
      .pop-item.d-flex
        .pop-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/lt-sm-8.jpg"}/
        .img-content
          %p
            %a{:href => ""} These sentences are selected from various online news.
          %ul.list-unstyled.list-inline
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
      .pop-item.d-flex
        .pop-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/lt-sm-9.jpg"}/
        .img-content
          %p
            %a{:href => ""} These sentences are selected from various online news.
          %ul.list-unstyled.list-inline
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
      .pop-item.d-flex
        .pop-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/lt-sm-12.jpg"}/
        .img-content
          %p
            %a{:href => ""} These sentences are selected from various online news.
          %ul.list-unstyled.list-inline
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
            %li.list-inline-item
              %i.fa.fa-star
    #comment.tab-pane.fade{:role => "tabpanel"}
      .com-item.d-flex
        .com-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/com-1.png"}/
        .img-content
          %p
            %a{:href => ""}
              %span> James
              \: Nesciunt quaerat ipsam fugiat impedit dignissimos unde...
      .com-item.d-flex
        .com-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/com-2.png"}/
        .img-content
          %p
            %a{:href => ""}
              %span> Mary
              \: Nesciunt quaerat ipsam fugiat impedit dignissimos unde...
      .com-item.d-flex
        .com-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/com-1.png"}/
        .img-content
          %p
            %a{:href => ""}
              %span> John
              \: Nesciunt quaerat ipsam fugiat impedit dignissimos unde...
      .com-item.d-flex
        .com-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/com-2.png"}/
        .img-content
          %p
            %a{:href => ""}
              %span> Anna
              \: Nesciunt quaerat ipsam fugiat impedit dignissimos unde...
      .com-item.d-flex
        .com-img
          %a{:href => ""}
            %img{:alt => "", :src => "images/com-1.png"}/
        .img-content
          %p
            %a{:href => ""}
              %span> Maxx
              \: Nesciunt quaerat ipsam fugiat impedit dignissimos unde...